_commit: 35ca7f1
_src_path: git@github.com:mizucopo/repo-template.git
author_email: mizu.copo@gmail.com
author_name: みず
docker_build_context: .
docker_image_name: switchbot-exporter
docker_login_username: mizucopo
docker_registry: mizucopo
docker_smoke_command: .venv/bin/python --version
dockerfile_path: Dockerfile
project_description: Prometheus SwitchBot Exporter
project_name: switchbot-exporter
project_version: 2.0.16
python_project_kind: application
python_version: '3.14'
use_aws_ecr: false
use_chrome_extension: false
use_dependabot_docker: true
use_dependabot_github_actions: true
use_docker: true
use_gh_actions_docker_quality: true
use_gh_actions_docker_release: true
use_gh_actions_pr_tag_check: true
use_mit_license: true
use_python: true
use_rust: false
use_tauri: false
repo_template_python_starters_created: true
repo_template_python_application_starter_created: true
repo_template_python_package_starter_names: []
repo_template_rust_starters_created: false
repo_template_chrome_starters_created: false
repo_template_tauri_starters_created: false
