FROM mizucopo/switchbot-exporter:latest

WORKDIR /app
COPY pyproject.toml uv.lock uv.dev.lock ./
RUN pip install --no-cache-dir uv \
  && uv pip install --system --no-deps --requirement uv.lock --requirement uv.dev.lock \
  && rm -rf /root/.cache/uv

CMD ["/bin/sh"]
