name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract branch name or tag
      id: ref
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "::set-output name=tag::$(echo $GITHUB_REF | sed 's|refs/tags/||')"
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          echo "::set-output name=tag::$(echo $GITHUB_REF | sed 's|refs/heads/||')"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./docker
        file: ./docker/Dockerfile.prod
        platforms: linux/amd64
        push: true
        tags: |
          mizucopo/switchbot-exporter:${{ steps.ref.outputs.tag == 'main' && 'latest' || steps.ref.outputs.tag }}
